INSERT INTO CINEMA(name,address,phone_number,email) VALUES ('Arena Cineplex','Bulevara Mihajla Pupina 3','063636363','cineplex@gmail.com');
INSERT INTO CINEMA(name,address,phone_number,email) VALUES ('Arena Cinestar','Bulevar Oslobodjenja 56','061121221','cinestar@gmail.com');
INSERT INTO USER(dtype,username,password,name,lastname,phone_number,email,activity,role,date) VALUES ('User', 'zixazmija','mihajlo99','Mihajlo','Zivkovic','0600233479','zixazmija99@gmail.com',true,2,'2019-09-09');
INSERT INTO USER(dtype,username,password,name,lastname,phone_number,email,activity,role,date) VALUES ('User', 'copor09','Nijyhu^72','Marko','Markovic','061764583','nikjughyu@gmail.com',false,1,'2020-01-01');
INSERT INTO USER(dtype,username,password,name,lastname,phone_number,email,activity,role,date) VALUES ('User', 'minicipelica','hamacada123','Lupur','Lupurovic','066666123','lupi@gmail.com',true,1,'2017-01-02');
INSERT INTO USER(dtype,username,password,name,lastname,phone_number,email,activity,role,date) VALUES ('User', 'stankovictab','djota','Djordje','Djordjevic','069696969','stanili@gmail.com',true,3,'2014-01-03');
INSERT INTO MOVIE(name,description,duration,genre,rating) VALUES ('The Lord of the Rings : The Fellowship of the Ring','',208,'Fantasy Fiction',0);
INSERT INTO MOVIE(name,description,duration,genre,rating) VALUES ('The Lord of the Rings : The Two Towers','',223,'Fantasy Fiction',0);
INSERT INTO MOVIE(name,description,duration,genre,rating) VALUES ('The Lord of the Rings : The Return of the King','',251,'Fantasy Fiction',0);
INSERT INTO MOVIE(name,description,duration,genre,rating) VALUES ('The Hobbit : An Unexpected Journey','',181,'Fantasy Fiction',0);
INSERT INTO MOVIE(name,description,duration,genre,rating) VALUES ('The Hobbit : The Desolation of Smaug','',187,'Fantasy Fiction',0);
INSERT INTO MOVIE(name,description,duration,genre,rating) VALUES ('The Hobbit : The Battle of the Five Armies','',179,'Fantasy Fiction',0);
INSERT INTO MOVIE(name,description,duration,genre,rating) VALUES ('Love Actually','',145,'Romantic Comedy',0);
INSERT INTO WATCHED_MOVIE(rating,viewer_id,movie_id) VALUES (9,3,1);
INSERT INTO WATCHED_MOVIE(rating,viewer_id,movie_id) VALUES (10,3,2);
INSERT INTO ROOM(capacity,mark,cinema_id) VALUES (200,'Sala 1',1);
INSERT INTO ROOM(capacity,mark,cinema_id) VALUES (80,'Sala 2',1);
INSERT INTO ROOM(capacity,mark,cinema_id) VALUES (60,'Sala 3',1);
INSERT INTO ROOM(capacity,mark,cinema_id) VALUES (250,'Sala 4',1);
INSERT INTO ROOM(capacity,mark,cinema_id) VALUES (400,'Sala 5',1);
INSERT INTO ROOM(capacity,mark,cinema_id) VALUES (250,'Hala 1',2);
INSERT INTO ROOM(capacity,mark,cinema_id) VALUES (120,'Hala 2',2);
INSERT INTO ROOM(capacity,mark,cinema_id) VALUES (50,'Hala 3',2);
INSERT INTO PROJECTION(day,price,cinema_id,movie_id) VALUES (2,450,1,3);
INSERT INTO PROJECTION(day,price,cinema_id,movie_id) VALUES (3,250,1,1);
INSERT INTO PROJECTION(day,price,cinema_id,movie_id) VALUES (2,350,2,6);
INSERT INTO PROJECTION(day,price,cinema_id,movie_id) VALUES (5,350,1,2);
INSERT INTO PROJECTION(day,price,cinema_id,movie_id) VALUES (6,450,2,5);
INSERT INTO ROOM_PROJECTION(room_id,projection_id) VALUES (1,1);
INSERT INTO ROOM_PROJECTION(room_id,projection_id) VALUES (2,3);
INSERT INTO RESERVATIONS(viewer_id,projection_id) VALUES (3,1);
INSERT INTO RESERVATIONS(viewer_id,projection_id) VALUES (2,1);

